<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Exported Orders - {{ $prompt->prompt }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 14px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #198754; /* Green for Exported/Done */
            padding-bottom: 20px;
        }

        .logo {
            max-width: 150px;
            max-height: 60px;
            margin-bottom: 15px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            color: #198754;
            margin: 10px 0 5px 0;
        }

        .tagline {
            font-size: 14px;
            color: #666;
            margin-bottom: 10px;
        }

        .category-info {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #198754;
        }

        .category-name {
            font-size: 16px;
            font-weight: bold;
            color: #198754;
            margin-bottom: 5px;
        }

        .prompt-name {
            font-size: 14px;
            color: #333;
        }

        .export-info {
            font-size: 9px;
            color: #999;
            text-align: right;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 12px;
        }

        th {
            background-color: #198754;
            color: white;
            padding: 8px 4px;
            text-align: center;
            font-weight: bold;
            border: 1px solid #157347;
        }

        td {
            padding: 6px 4px;
            border: 1px solid #ddd;
            vertical-align: top;
            text-align: center;
        }

        tr:nth-child(even) {
            background-color: #f8f9fa;
        }

        .footer {
            position: fixed;
            bottom: 20px;
            left: 20px;
            right: 20px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        @if(isset($settings->logo))
            <img src="{{ public_path('img/'.$settings->logo) }}" class="logo" alt="Logo">
        @else
            <h2>{{ $settings->title ?? 'Moon Enterprises' }}</h2>
        @endif
        <div class="title">Exported Orders Report</div>
        <div class="tagline">Generated on {{ date('d M, Y') }}</div>
    </div>

    <div class="category-info">
        @if($category)
        <div class="category-name">Category: {{ $category->name }}</div>
        @endif
        <div class="prompt-name">Prompt: {{ $prompt->prompt }} ({{ $prompt->number_start }} - {{ $prompt->number_end }})</div>
    </div>

    <div class="export-info">
        Report generated by Admin | {{ date('Y-m-d H:i:s') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Ser</th>
                <th>RTTP</th>
                <th>First</th>
                <th>Second</th>
                <th>Subtracted Amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @php
                $counter = 1;
                $totalFirst = 0;
                $totalSecond = 0;
            @endphp
            @foreach($exportedOrdersData as $rttpValue => $data)
            @php
                $totalFirst += $data['first'];
                $totalSecond += $data['second'];
            @endphp
            <tr>
                <td>{{ $counter++ }}</td>
                <td>
                    {{ $rttpValue }}
                </td>
                <td>{{ $data['first'] }}</td>
                <td>{{ $data['second'] }}</td>
                <td>
                    @if($data['cut_first'] > 0 || $data['cut_second'] > 0)
                        <div style="color: #856404;">
                            @if($data['cut_first'] > 0) First: -{{ $data['cut_first'] }} @endif
                            @if($data['cut_first'] > 0 && $data['cut_second'] > 0) <br> @endif
                            @if($data['cut_second'] > 0) Second: -{{ $data['cut_second'] }} @endif
                        </div>
                    @else
                        <span style="color: #999;">-</span>
                    @endif
                </td>
                <td style="color: #198754; font-weight: bold;">Exported</td>
            </tr>
            @endforeach
            <tr style="background-color: #f8f9fa; font-weight: bold;">
                <td colspan="2" style="text-align: right;">Total:</td>
                <td>{{ $totalFirst }}</td>
                <td>{{ $totalSecond }}</td>
                <td colspan="2"></td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        &copy; {{ date('Y') }} {{ $settings->title ?? 'Moon Enterprises' }}. All rights reserved.
    </div>
</body>
</html>
